// Take it, use it and share it.
// Human knowledge belongs to the world

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author whosyourdaddy
 */
public class FrameResult extends javax.swing.JFrame implements Runnable {
    
    Object[] field = {"Name", "Full Path"};
    DefaultTableModel defModel = new DefaultTableModel(null, field);
    Thread th;
    String keyWord;
    ArrayList drive = new ArrayList();

    /**
     * Creates new form FrameResult
     */
    public FrameResult(String str) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        tblResult.setModel(defModel);
        keyWord = str;
        this.setTitle("Search Result for : " + str);
        th = new Thread(this);
        th.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        menuOpen = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnStop = new javax.swing.JButton();
        lblPath = new javax.swing.JLabel();
        lblFound = new javax.swing.JLabel();

        menuOpen.setText("jMenuItem1");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        popMenu.add(menuOpen);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hasil Pencarian");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResult);

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stop.png"))); // NOI18N
        btnStop.setText("Stop Search");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblPath.setText("jLabel1");

        lblFound.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPath)
                            .addComponent(lblFound))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStop)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStop)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFound)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
       File folder;
        try {
            int row = tblResult.getSelectedRow();
            File f = new File((String) defModel.getValueAt(row, 1));
            if (f.isDirectory()) {
                folder = f;
            } else {
                folder = new File(new File((String) defModel.getValueAt(row, 1)).getParent());
            }
            Runtime.getRuntime().exec("explorer.exe " + folder.getAbsolutePath());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable To Open Folder");
        }
    }//GEN-LAST:event_menuOpenActionPerformed

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            tblResult.changeSelection(tblResult.rowAtPoint(tblResult.getMousePosition()), 0, false, false);
            popMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblResultMouseClicked

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        th.stop();
        lblPath.setText("Searching is stopped...");
    }//GEN-LAST:event_btnStopActionPerformed

    public void getAllDrive() {
        File roots[] = File.listRoots();
        for (int i = 0; i < roots.length; i++) {
            drive.add(roots[i].toString());
        }
    }
    
    public void search(File f) {
        try {
            String[] str = f.list();
            for (int i = 0; i < str.length; i++) {
                File fl = new File(f.getAbsolutePath(), str[i]);
                boolean bol = false;
                lblPath.setText(fl.getAbsolutePath());

                for (int j = 0; j <= str[i].length() - keyWord.length(); j++) {
                    if (str[i].substring(j, j + keyWord.length()).equalsIgnoreCase(keyWord)) {
                        bol = true;
                        break;
                    }
                }

                if (bol) {
                    Vector vec = new Vector();
                    vec.addElement(fl.getName());
                    vec.addElement(fl.getAbsolutePath());
                    defModel.addRow(vec);
                    lblFound.setText("Found: " + String.valueOf(defModel.getRowCount()));
                }
                if (fl.isDirectory() && fl.canRead()) {
                    search(fl);
                }
            }
        } catch (Exception e) {
        }
    }
    
    public void run() {
        getAllDrive();
        for (int i = 0; i < drive.size(); i++) {
            File f = new File(drive.get(i).toString());
            if (f.exists() && f.canRead()) {
                search(f);
            }
        }
        lblPath.setText("Searching is finished...");
        btnStop.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFound;
    private javax.swing.JLabel lblPath;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
