// Take it, use it and share it.
// Human knowledge belongs to the world

import java.awt.Dimension;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author whosyourdaddy
 */
public class FrameUtama extends javax.swing.JFrame {

    boolean mousePressed;
    int relativeX, relativeY;
    
    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
        addTrayIcon();
        Dimension scrnsize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) (scrnsize.width - this.getWidth()) / 2, (int) (scrnsize.height - this.getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new java.awt.PopupMenu();
        menuHide = new java.awt.MenuItem();
        menuQuit = new java.awt.MenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        popMenu.setLabel("Menu");
        popMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMenuActionPerformed(evt);
            }
        });

        menuHide.setLabel("Hide Window");
        menuHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHideActionPerformed(evt);
            }
        });
        popMenu.add(menuHide);
        popMenu.addSeparator();
        menuQuit.setLabel("Quit Window");
        menuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitActionPerformed(evt);
            }
        });
        popMenu.add(menuQuit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-icon.png"))); // NOI18N

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String keyWord = txtSearch.getText();
        txtSearch.setText("");
        new FrameResult(keyWord).setVisible(true);
    }//GEN-LAST:event_txtSearchActionPerformed

    private void menuHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHideActionPerformed
        if(menuHide.getLabel().equals("Hide Window")){
            this.hide();
            menuHide.setLabel("Show Window");
        } else {
            this.show();
            menuHide.setLabel("Hide Window");
        }
    }//GEN-LAST:event_menuHideActionPerformed

    private void menuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuQuitActionPerformed

    private void popMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popMenuActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
        mousePressed = true;
        relativeX = evt.getX();
        relativeY = evt.getY();
    }                                 

    private void formMouseReleased(java.awt.event.MouseEvent evt) {                                   
        mousePressed = false;
    }                                  

    private void formMouseDragged(java.awt.event.MouseEvent evt) {                                  
        if (mousePressed) {
            int absX = this.getLocationOnScreen().x + evt.getX();
            int absY = this.getLocationOnScreen().y + evt.getY();
            int x = absX - relativeX;
            int y = absY - relativeY;
            this.setLocation(x, y);
        }
    }                                 

    private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
        if (evt.getButton() == MouseEvent.BUTTON3) {
            popMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }                                 
                                          
    public void addTrayIcon() {
        ImageIcon icon = new ImageIcon("icon/search_trayicon.png"); 
        Image img = icon.getImage();
        TrayIcon tray = new TrayIcon(img, "Menu Search", popMenu);
        SystemTray sysTray = SystemTray.getSystemTray();
        try {
            sysTray.add(tray);
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameUtama().setVisible(true);


            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.MenuItem menuHide;
    private java.awt.MenuItem menuQuit;
    private java.awt.PopupMenu popMenu;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
